blank_issues_enabled: true
contact_links:
  - name: User support issue
    url: https://put-some-link-here-to-user-support.com
    about: Need help with your installation? Reach out to our user support.
